const url = 'https://moddyvtltodywvtzzwft.supabase.co/rest/v1/proguns_estoque'
const key = 'sb_publishable_8saf-ghPOB_703jfDbdT3A_DVvRjYLr'

export const ITENS_TESTE = [
  // ─── 1. ARMAS DE FOGO (10 ITENS) ───
  {
    id: 'arma_01',
    tipo_estoque: 'ARMA',
    codigo_sku: 'ABT104821',
    nome: 'Pistola Taurus G3c T.O.R.O. 9x19mm',
    categoria: 'Armas de Fogo',
    numero_serie: 'ABT104821',
    tipo_arma: 'Pistola',
    fabricante: 'Taurus',
    modelo: 'G3c T.O.R.O.',
    calibre: '9x19mm Luger',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SIGMA',
    numero_sigma_sinarm: 'SIGMA-2026-9481',
    status_arma: 'DISPONIVEL',
    preco_custo: 3200,
    preco_venda: 4850,
    acabamento: 'Teniferizado Preto',
    comprimento_cano: '3.26 pol',
    capacidade_tiros: '12+1',
    localizacao: 'Cofre A - Gaveta 1',
    codigo_barras: '7891115001011',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_02',
    tipo_estoque: 'ARMA',
    codigo_sku: 'BKL92410',
    nome: 'Pistola Glock G19 Gen5 MOS 9x19mm',
    categoria: 'Armas de Fogo',
    numero_serie: 'BKL92410',
    tipo_arma: 'Pistola',
    fabricante: 'Glock',
    modelo: 'G19 Gen5 MOS',
    calibre: '9x19mm Luger',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SIGMA',
    numero_sigma_sinarm: 'SIGMA-2026-1029',
    status_arma: 'DISPONIVEL',
    preco_custo: 6800,
    preco_venda: 9900,
    acabamento: 'nDLC Preto Fosco',
    comprimento_cano: '4.02 pol',
    capacidade_tiros: '15+1',
    localizacao: 'Cofre A - Gaveta 1',
    codigo_barras: '764503037252',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_03',
    tipo_estoque: 'ARMA',
    codigo_sku: 'TS988231',
    nome: 'Pistola Taurus TS9 Full Size 9x19mm',
    categoria: 'Armas de Fogo',
    numero_serie: 'TS988231',
    tipo_arma: 'Pistola',
    fabricante: 'Taurus',
    modelo: 'TS9 Full Size',
    calibre: '9x19mm Luger',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SINARM',
    numero_sigma_sinarm: 'SINARM-GO-2026-44',
    status_arma: 'DISPONIVEL',
    preco_custo: 3400,
    preco_venda: 4990,
    acabamento: 'Teniferizado Preto',
    comprimento_cano: '4.0 pol',
    capacidade_tiros: '17+1',
    localizacao: 'Cofre A - Gaveta 2',
    codigo_barras: '7891115003022',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_04',
    tipo_estoque: 'ARMA',
    codigo_sku: 'GX402194',
    nome: 'Pistola Taurus GX4 Micro-Compact 9x19mm',
    categoria: 'Armas de Fogo',
    numero_serie: 'GX402194',
    tipo_arma: 'Pistola',
    fabricante: 'Taurus',
    modelo: 'GX4 Micro-Compact',
    calibre: '9x19mm Luger',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SIGMA',
    numero_sigma_sinarm: 'SIGMA-2026-5512',
    status_arma: 'RESERVADA',
    cliente_reserva_nome: 'Marcos Vinicius Pereira',
    preco_custo: 2950,
    preco_venda: 4400,
    acabamento: 'Cerakote Sniper Green',
    comprimento_cano: '3.06 pol',
    capacidade_tiros: '11+1',
    localizacao: 'Cofre A - Gaveta 2 (Reservados)',
    codigo_barras: '7891115004033',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_05',
    tipo_estoque: 'ARMA',
    codigo_sku: 'RT382910',
    nome: 'Revólver Taurus RT 856 Defender .38 SPL 6T',
    categoria: 'Armas de Fogo',
    numero_serie: 'RT382910',
    tipo_arma: 'Revólver',
    fabricante: 'Taurus',
    modelo: 'RT 856 Defender',
    calibre: '.38 SPL',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SINARM',
    status_arma: 'DISPONIVEL',
    preco_custo: 2800,
    preco_venda: 4150,
    acabamento: 'Inox Fosco',
    comprimento_cano: '3.0 pol',
    capacidade_tiros: '6 tiros',
    localizacao: 'Cofre A - Gaveta 3',
    codigo_barras: '7891115005044',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_06',
    tipo_estoque: 'ARMA',
    codigo_sku: 'RT627884',
    nome: 'Revólver Taurus RT 627 Tracker .357 Mag 7T',
    categoria: 'Armas de Fogo',
    numero_serie: 'RT627884',
    tipo_arma: 'Revólver',
    fabricante: 'Taurus',
    modelo: 'RT 627 Tracker 7 Tiros',
    calibre: '.357 Magnum',
    classificacao_calibre: 'RESTRITO',
    sistema_registro: 'SIGMA',
    status_arma: 'DISPONIVEL',
    preco_custo: 4100,
    preco_venda: 5950,
    acabamento: 'Inox c/ Compensador',
    comprimento_cano: '4.0 pol',
    capacidade_tiros: '7 tiros',
    localizacao: 'Cofre A - Restritos',
    codigo_barras: '7891115006055',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_07',
    tipo_estoque: 'ARMA',
    codigo_sku: 'IMB450912',
    nome: 'Pistola Imbel 1911 TC MD1 .45 ACP',
    categoria: 'Armas de Fogo',
    numero_serie: 'IMB450912',
    tipo_arma: 'Pistola',
    fabricante: 'Imbel',
    modelo: '1911 TC MD1',
    calibre: '.45 ACP',
    classificacao_calibre: 'RESTRITO',
    sistema_registro: 'SIGMA',
    status_arma: 'DISPONIVEL',
    preco_custo: 4600,
    preco_venda: 6800,
    acabamento: 'Fosfatizado Preto Militar',
    comprimento_cano: '4.25 pol',
    capacidade_tiros: '8+1',
    localizacao: 'Cofre A - Restritos',
    codigo_barras: '7891115007066',
    ncm: '9302.00.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_08',
    tipo_estoque: 'ARMA',
    codigo_sku: 'T4556019',
    nome: 'Fuzil Taurus T4 M-Lok 5.56x45mm 14.5 pol',
    categoria: 'Armas de Fogo',
    numero_serie: 'T4556019',
    tipo_arma: 'Fuzil',
    fabricante: 'Taurus',
    modelo: 'T4 M-Lok 14.5 pol',
    calibre: '5.56x45mm (.223)',
    classificacao_calibre: 'RESTRITO',
    sistema_registro: 'SIGMA',
    status_arma: 'AGUARDANDO_CRAF',
    cliente_reserva_nome: 'Eduardo Santos Rocha',
    preco_custo: 9800,
    preco_venda: 14900,
    acabamento: 'Anodizado Preto Fosco',
    comprimento_cano: '14.5 pol',
    capacidade_tiros: '30+1',
    localizacao: 'Cofre B - Fuzis',
    codigo_barras: '7891115008077',
    ncm: '9303.30.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_09',
    tipo_estoque: 'ARMA',
    codigo_sku: 'CBC702281',
    nome: 'Carabina CBC 7022 Way .22 LR Semiauto',
    categoria: 'Armas de Fogo',
    numero_serie: 'CBC702281',
    tipo_arma: 'Carabina',
    fabricante: 'CBC',
    modelo: '7022 Way Coronha Tática',
    calibre: '.22 LR',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SIGMA',
    status_arma: 'DISPONIVEL',
    preco_custo: 1600,
    preco_venda: 2650,
    acabamento: 'Oxidado / Polímero',
    comprimento_cano: '18 pol',
    capacidade_tiros: '10+1',
    localizacao: 'Cofre B - Longas',
    codigo_barras: '7891115009088',
    ncm: '9303.30.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },
  {
    id: 'arma_10',
    tipo_estoque: 'ARMA',
    codigo_sku: 'BOI120938',
    nome: 'Espingarda Boito Standard Pump 12 GA 24 pol',
    categoria: 'Armas de Fogo',
    numero_serie: 'BOI120938',
    tipo_arma: 'Espingarda',
    fabricante: 'Rossi',
    modelo: 'Boito Pump 12/24 pol',
    calibre: '12 GA',
    classificacao_calibre: 'PERMITIDO',
    sistema_registro: 'SIGMA',
    status_arma: 'DISPONIVEL',
    preco_custo: 3100,
    preco_venda: 4700,
    acabamento: 'Oxidado Negro',
    comprimento_cano: '24 pol',
    capacidade_tiros: '7+1',
    localizacao: 'Cofre B - Longas',
    codigo_barras: '7891115010099',
    ncm: '9303.30.00',
    unidade: 'UN',
    quantidade: 1,
    estoque_minimo: 1
  },

  // ─── 2. MUNIÇÕES (10 ITENS) ───
  {
    id: 'mun_01',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-9MM-L12',
    nome: 'Munição CBC 9mm Luger ETOG 115gr Treino',
    categoria: 'Munições',
    calibre: '9x19mm Luger',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L12',
    tipo_projetil: 'ETOG - Encamisado Total Ogival (Treino)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 30,
    quantidade: 1500,
    estoque_minimo: 5,
    preco_caixa: 220,
    preco_custo: 145,
    preco_venda: 220,
    preco_unitario_cartucho: 4.40,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116001018',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_02',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-9MM-BOND-L19',
    nome: 'Munição CBC 9mm Luger EXPO 124gr Bonded Defesa',
    categoria: 'Munições',
    calibre: '9x19mm Luger',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L19',
    tipo_projetil: 'Bonded (Alta Performance Policial)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 15,
    quantidade: 750,
    estoque_minimo: 3,
    preco_caixa: 390,
    preco_custo: 260,
    preco_venda: 390,
    preco_unitario_cartucho: 7.80,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116002025',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_03',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-380-L24',
    nome: 'Munição CBC .380 Auto ETOG 95gr Treino',
    categoria: 'Munições',
    calibre: '.380 ACP',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L24',
    tipo_projetil: 'ETOG - Encamisado Total Ogival (Treino)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 20,
    quantidade: 1000,
    estoque_minimo: 4,
    preco_caixa: 235,
    preco_custo: 155,
    preco_venda: 235,
    preco_unitario_cartucho: 4.70,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116003032',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_04',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-380-GOLD-L28',
    nome: 'Munição CBC .380 Auto EXPO 95gr Gold Dot Defesa',
    categoria: 'Munições',
    calibre: '.380 ACP',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L28',
    tipo_projetil: 'EXPO - Ponta Oca Expansivo (Defesa / Porte)',
    apresentacao_embalagem: 'Caixa c/ 20 cartuchos',
    quantidade_por_embalagem: 20,
    total_caixas: 10,
    quantidade: 200,
    estoque_minimo: 2,
    preco_caixa: 195,
    preco_custo: 130,
    preco_venda: 195,
    preco_unitario_cartucho: 9.75,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116004049',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_05',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-38SPL-L31',
    nome: 'Munição CBC .38 SPL Chumbo Ogival 158gr',
    categoria: 'Munições',
    calibre: '.38 SPL',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L31',
    tipo_projetil: 'Chumbo Ogival (Lazer / Stand)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 12,
    quantidade: 600,
    estoque_minimo: 3,
    preco_caixa: 240,
    preco_custo: 160,
    preco_venda: 240,
    preco_unitario_cartucho: 4.80,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116005056',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_06',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-40SW-L42',
    nome: 'Munição CBC .40 S&W ETOG 180gr',
    categoria: 'Munições',
    calibre: '.40 S&W',
    classificacao_calibre: 'RESTRITO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L42',
    tipo_projetil: 'ETOG - Encamisado Total Ogival (Treino)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 8,
    quantidade: 400,
    estoque_minimo: 2,
    preco_caixa: 320,
    preco_custo: 210,
    preco_venda: 320,
    preco_unitario_cartucho: 6.40,
    localizacao: 'Cofre B - Munições Restritas',
    codigo_barras: '7891116006063',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_07',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-45ACP-L47',
    nome: 'Munição CBC .45 ACP ETOG 230gr Ball',
    categoria: 'Munições',
    calibre: '.45 ACP',
    classificacao_calibre: 'RESTRITO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L47',
    tipo_projetil: 'ETOG - Encamisado Total Ogival (Treino)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 6,
    quantidade: 300,
    estoque_minimo: 2,
    preco_caixa: 360,
    preco_custo: 240,
    preco_venda: 360,
    preco_unitario_cartucho: 7.20,
    localizacao: 'Cofre B - Munições Restritas',
    codigo_barras: '7891116007070',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_08',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-12GA-L55',
    nome: 'Munição CBC 12 GA Velox Chumbo 3T 32g',
    categoria: 'Munições',
    calibre: '12 GA Velox',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L55',
    tipo_projetil: 'Balote / Chumbo 3T / SG (12GA)',
    apresentacao_embalagem: 'Caixa c/ 25 cartuchos',
    quantidade_por_embalagem: 25,
    total_caixas: 16,
    quantidade: 400,
    estoque_minimo: 3,
    preco_caixa: 185,
    preco_custo: 125,
    preco_venda: 185,
    preco_unitario_cartucho: 7.40,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116008087',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_09',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-556-SS109-L63',
    nome: 'Munição CBC 5.56x45mm NATO SS109 62gr Fuzil',
    categoria: 'Munições',
    calibre: '5.56x45mm (.223)',
    classificacao_calibre: 'RESTRITO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L63',
    tipo_projetil: 'ETOG - Encamisado Total Ogival (Treino)',
    apresentacao_embalagem: 'Caixa c/ 20 cartuchos',
    quantidade_por_embalagem: 20,
    total_caixas: 25,
    quantidade: 500,
    estoque_minimo: 5,
    preco_caixa: 175,
    preco_custo: 110,
    preco_venda: 175,
    preco_unitario_cartucho: 8.75,
    localizacao: 'Cofre B - Munições Restritas',
    codigo_barras: '7891116009094',
    ncm: '9306.30.00',
    unidade: 'CX'
  },
  {
    id: 'mun_10',
    tipo_estoque: 'MUNICAO',
    codigo_sku: 'MUN-22LR-L70',
    nome: 'Munição CBC .22 LR Target Solid 40gr',
    categoria: 'Munições',
    calibre: '.22 LR',
    classificacao_calibre: 'PERMITIDO',
    fabricante: 'CBC',
    lote_fabricante: 'CBC-2026-L70',
    tipo_projetil: 'Chumbo Ogival (Lazer / Stand)',
    apresentacao_embalagem: 'Caixa c/ 50 cartuchos',
    quantidade_por_embalagem: 50,
    total_caixas: 40,
    quantidade: 2000,
    estoque_minimo: 5,
    preco_caixa: 70,
    preco_custo: 45,
    preco_venda: 70,
    preco_unitario_cartucho: 1.40,
    localizacao: 'Cofre B - Munições',
    codigo_barras: '7891116010014',
    ncm: '9306.30.00',
    unidade: 'CX'
  },

  // ─── 3. PEÇAS & COMPONENTES (10 ITENS) ───
  {
    id: 'peca_01',
    tipo_estoque: 'PECA',
    codigo_sku: 'GLK-EXT-G5-9',
    nome: 'Extrator Glock Gen5 9mm Original',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117001017',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 120,
    preco_venda: 250,
    quantidade: 8,
    estoque_minimo: 2,
    localizacao: 'Gaveta A1 - Armeria'
  },
  {
    id: 'peca_02',
    tipo_estoque: 'PECA',
    codigo_sku: 'TAU-PERC-T4',
    nome: 'Percussor Taurus T4 Fuzil 5.56 Inox',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117002024',
    ncm: '9305.20.00',
    unidade: 'PC',
    preco_custo: 95,
    preco_venda: 220,
    quantidade: 4,
    estoque_minimo: 2,
    localizacao: 'Gaveta B3 - Armeria'
  },
  {
    id: 'peca_03',
    tipo_estoque: 'PECA',
    codigo_sku: 'GLK-MOL-G19G5',
    nome: 'Mola Recuperadora Dupla Glock G19 Gen5',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117003031',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 180,
    preco_venda: 340,
    quantidade: 6,
    estoque_minimo: 2,
    localizacao: 'Gaveta A2 - Armeria'
  },
  {
    id: 'peca_04',
    tipo_estoque: 'PECA',
    codigo_sku: 'TAU-MOL-G3C-KIT',
    nome: 'Kit Molas Aliviadas de Gatilho Taurus G2c/G3c',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117004048',
    ncm: '9305.10.00',
    unidade: 'JG',
    preco_custo: 65,
    preco_venda: 140,
    quantidade: 12,
    estoque_minimo: 3,
    localizacao: 'Gaveta B1 - Armeria'
  },
  {
    id: 'peca_05',
    tipo_estoque: 'PECA',
    codigo_sku: 'GLK-RET-MAG-EXT',
    nome: 'Retém do Carregador Estendido Glock Gen4/5 Alumínio',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117005055',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 85,
    preco_venda: 175,
    quantidade: 7,
    estoque_minimo: 2,
    localizacao: 'Gaveta A3 - Armeria'
  },
  {
    id: 'peca_06',
    tipo_estoque: 'PECA',
    codigo_sku: 'TAU-PERC-TITAN',
    nome: 'Percussor em Titânio Taurus G2c / G3c / TS9',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117006062',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 110,
    preco_venda: 230,
    quantidade: 5,
    estoque_minimo: 2,
    localizacao: 'Gaveta B2 - Armeria'
  },
  {
    id: 'peca_07',
    tipo_estoque: 'PECA',
    codigo_sku: 'GLK-MIR-TRITIUM',
    nome: 'Conjunto Alça e Massa Trítio Noturna Glock',
    categoria: 'MIRAS & ÓPTICAS',
    codigo_barras: '7891117007079',
    ncm: '9305.10.00',
    unidade: 'JG',
    preco_custo: 380,
    preco_venda: 680,
    quantidade: 3,
    estoque_minimo: 1,
    localizacao: 'Vitrine A1'
  },
  {
    id: 'peca_08',
    tipo_estoque: 'PECA',
    codigo_sku: 'IMB-EJET-1911',
    nome: 'Ejetor de Cartuchos Imbel 1911 .45 ACP',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117008086',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 75,
    preco_venda: 160,
    quantidade: 5,
    estoque_minimo: 2,
    localizacao: 'Gaveta C1 - Armeria'
  },
  {
    id: 'peca_09',
    tipo_estoque: 'PECA',
    codigo_sku: 'TAU-MOL-CAO-RT',
    nome: 'Mola do Cão / Percussão Revólver Taurus RT 856/889',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117009093',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 35,
    preco_venda: 85,
    quantidade: 10,
    estoque_minimo: 3,
    localizacao: 'Gaveta C2 - Armeria'
  },
  {
    id: 'peca_10',
    tipo_estoque: 'PECA',
    codigo_sku: 'GLK-GUIA-INOX',
    nome: 'Guia de Mola em Aço Inox Polido Glock G17/G19',
    categoria: 'COMPONENTES & PEÇAS',
    codigo_barras: '7891117010010',
    ncm: '9305.10.00',
    unidade: 'PC',
    preco_custo: 140,
    preco_venda: 260,
    quantidade: 6,
    estoque_minimo: 2,
    localizacao: 'Gaveta A2 - Armeria'
  },

  // ─── 4. SUPRIMENTOS & ACESSÓRIOS (10 ITENS) ───
  {
    id: 'sup_01',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'SUP-LUB-PRO-100',
    nome: 'Óleo Lubrificante Sintético Tático Pró Guns 100ml',
    categoria: 'LIMPEZA & CONSERVAÇÃO',
    codigo_barras: '7891118001016',
    ncm: '3403.99.00',
    unidade: 'ML',
    preco_custo: 18,
    preco_venda: 45,
    quantidade: 25,
    estoque_minimo: 5,
    localizacao: 'Prateleira C - Balcão'
  },
  {
    id: 'sup_02',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'SUP-SOLV-CHUMBO',
    nome: 'Solvente Desincrustante de Chumbo e Cobre 120ml',
    categoria: 'LIMPEZA & CONSERVAÇÃO',
    codigo_barras: '7891118002023',
    ncm: '3403.99.00',
    unidade: 'ML',
    preco_custo: 24,
    preco_venda: 55,
    quantidade: 18,
    estoque_minimo: 4,
    localizacao: 'Prateleira C - Balcão'
  },
  {
    id: 'sup_03',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'SUP-DESENG-AERO',
    nome: 'Desengraxante a Seco Tático Aerossol 300ml',
    categoria: 'LIMPEZA & CONSERVAÇÃO',
    codigo_barras: '7891118003030',
    ncm: '3403.99.00',
    unidade: 'ML',
    preco_custo: 32,
    preco_venda: 68,
    quantidade: 14,
    estoque_minimo: 3,
    localizacao: 'Prateleira C - Balcão'
  },
  {
    id: 'sup_04',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'SUP-BORE-9MM',
    nome: 'Bore Snake Cabo de Limpeza Rápida Calibre 9mm / .380',
    categoria: 'LIMPEZA & CONSERVAÇÃO',
    codigo_barras: '7891118004047',
    ncm: '9305.10.00',
    unidade: 'UN',
    preco_custo: 28,
    preco_venda: 65,
    quantidade: 10,
    estoque_minimo: 2,
    localizacao: 'Expositor Armeria'
  },
  {
    id: 'sup_05',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'SUP-BORE-556',
    nome: 'Bore Snake Cabo de Limpeza Rápida Calibre 5.56 / .223',
    categoria: 'LIMPEZA & CONSERVAÇÃO',
    codigo_barras: '7891118005054',
    ncm: '9305.20.00',
    unidade: 'UN',
    preco_custo: 30,
    preco_venda: 70,
    quantidade: 8,
    estoque_minimo: 2,
    localizacao: 'Expositor Armeria'
  },
  {
    id: 'sup_06',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'SUP-BORE-12GA',
    nome: 'Bore Snake Cabo de Limpeza Rápida Calibre 12 GA',
    categoria: 'LIMPEZA & CONSERVAÇÃO',
    codigo_barras: '7891118006061',
    ncm: '9305.20.00',
    unidade: 'UN',
    preco_custo: 35,
    preco_venda: 75,
    quantidade: 6,
    estoque_minimo: 2,
    localizacao: 'Expositor Armeria'
  },
  {
    id: 'sup_07',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'ACS-COL-G3C-KYDEX',
    nome: 'Coldre Velado Kydex Premium Taurus G3c Destro',
    categoria: 'ACESSÓRIOS & CARREGADORES',
    codigo_barras: '7891118007078',
    ncm: '4202.92.00',
    unidade: 'UN',
    preco_custo: 110,
    preco_venda: 230,
    quantidade: 8,
    estoque_minimo: 2,
    localizacao: 'Prateleira Acessórios'
  },
  {
    id: 'sup_08',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'ACS-COL-G19-KYDEX',
    nome: 'Coldre Velado Kydex Premium Glock G19 Destro',
    categoria: 'ACESSÓRIOS & CARREGADORES',
    codigo_barras: '7891118008085',
    ncm: '4202.92.00',
    unidade: 'UN',
    preco_custo: 120,
    preco_venda: 245,
    quantidade: 6,
    estoque_minimo: 2,
    localizacao: 'Prateleira Acessórios'
  },
  {
    id: 'sup_09',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'ACS-ABAF-ELET-PRO',
    nome: 'Abafador Eletrônico Tático Redução Ruído 22dB',
    categoria: 'ACESSÓRIOS & CARREGADORES',
    codigo_barras: '7891118009092',
    ncm: '9004.90.90',
    unidade: 'UN',
    preco_custo: 210,
    preco_venda: 390,
    quantidade: 5,
    estoque_minimo: 2,
    localizacao: 'Vitrine EPI'
  },
  {
    id: 'sup_10',
    tipo_estoque: 'SUPRIMENTO',
    codigo_sku: 'ACS-OCULOS-MIL-3L',
    nome: 'Óculos de Proteção Balística Militar 3 Lentes',
    categoria: 'ACESSÓRIOS & CARREGADORES',
    codigo_barras: '7891118010012',
    ncm: '9004.90.90',
    unidade: 'UN',
    preco_custo: 130,
    preco_venda: 260,
    quantidade: 7,
    estoque_minimo: 2,
    localizacao: 'Vitrine EPI'
  }
]

async function seed() {
  console.log(`Enviando ${ITENS_TESTE.length} itens de teste para o Supabase...`)
  let sucessos = 0
  let falhas = 0
  for (const item of ITENS_TESTE) {
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          apikey: key,
          Authorization: 'Bearer ' + key,
          'Content-Type': 'application/json',
          Prefer: 'resolution=merge-duplicates'
        },
        body: JSON.stringify(item)
      })
      if (!res.ok) {
        const text = await res.text()
        console.error(`Erro ao inserir ${item.id} (${item.nome}):`, text)
        falhas++
      } else {
        sucessos++
        console.log(`[OK ${sucessos}/40] Inserido: ${item.nome}`)
      }
    } catch (err) {
      console.error(`Exceção ao inserir ${item.nome}:`, err)
      falhas++
    }
  }
  console.log(`\n========================================`)
  console.log(`FINALIZADO: ${sucessos} itens com sucesso, ${falhas} falhas.`)
  console.log(`========================================`)
}

if (typeof process !== 'undefined' && process.argv && process.argv[1]?.includes('seedEstoque')) {
  seed()
}
